// Generated by tools/generate_localization.py. Do not edit by hand.
// Edit localization/strings.toml, then run the generator.
#pragma once

#include <stdint.h>

enum class UiLanguage : uint8_t {
	English = 0,
	Spanish,
	French,
	German,
	Romanian,
	Polish,
	Count,
};

enum class UiText : uint8_t {
	Resume = 0,
	Chapters,
	Library,
	Settings,
	UsbTransfer,
	PowerOff,
	Back,
	Display,
	TypographyTune,
	WordPacing,
	Theme,
	Brightness,
	Language,
	ReadingMode,
	LongWords,
	Complexity,
	Punctuation,
	ResetPacing,
	Night,
	Dark,
	Light,
	On,
	Off,
	FontSize,
	Typeface,
	PhantomWords,
	RedHighlight,
	Tracking,
	Anchor,
	GuideWidth,
	GuideGap,
	Reset,
	Typography,
	TapToExit,
	TapToReset,
	TapChangeSample,
	TapExitSample,
	TapToggleSample,
	TapCycleSample,
	CurrentBook,
	Start,
	StartOfBook,
	RestartBook,
	AreYouSure,
	NoKeepPlace,
	YesRestart,
	NoSamples,
	Large,
	Medium,
	Small,
	Standard,
	RsvpMode,
	ScrollMode,
	TimeEstimate,
	TimeEstimateAccurate,
	TimeEstimateFast,
	Count,
};

namespace Localization {

UiLanguage sanitizeLanguage(uint8_t value);
UiLanguage nextLanguage(UiLanguage current);
const char *languageName(UiLanguage language);
const char *text(UiLanguage language, UiText key);

}  // namespace Localization
