// Generated by tools/generate_localization.py. Do not edit by hand.
// Edit localization/strings.toml, then run the generator.
#include "Localization.h"

#include <array>
#include <cstddef>

namespace {

constexpr size_t kLanguageCount = static_cast<size_t>(UiLanguage::Count);
constexpr size_t kTextCount = static_cast<size_t>(UiText::Count);
constexpr size_t kDefaultLanguageIndex = 0;
constexpr uint16_t kMissingOffset = 0xFFFF;

static_assert(kLanguageCount == 6, "UiLanguage count mismatch");
static_assert(kTextCount == 56, "UiText count mismatch");

constexpr char kStringBlob[] =
	/*     0 */ "English\0"
	/*     8 */ "Espanol\0"
	/*    16 */ "Francais\0"
	/*    25 */ "Deutsch\0"
	/*    33 */ "Romana\0"
	/*    40 */ "Polski\0"
	/*    47 */ "Resume\0"
	/*    54 */ "Chapters\0"
	/*    63 */ "Library\0"
	/*    71 */ "Settings\0"
	/*    80 */ "USB transfer\0"
	/*    93 */ "Power off\0"
	/*   103 */ "Back\0"
	/*   108 */ "Display\0"
	/*   116 */ "Typography tune\0"
	/*   132 */ "Word pacing\0"
	/*   144 */ "Theme\0"
	/*   150 */ "Brightness\0"
	/*   161 */ "Language\0"
	/*   170 */ "Reading mode\0"
	/*   183 */ "Long words\0"
	/*   194 */ "Complexity\0"
	/*   205 */ "Punctuation\0"
	/*   217 */ "Reset pacing\0"
	/*   230 */ "Night\0"
	/*   236 */ "Dark\0"
	/*   241 */ "Light\0"
	/*   247 */ "On\0"
	/*   250 */ "Off\0"
	/*   254 */ "Font size\0"
	/*   264 */ "Typeface\0"
	/*   273 */ "Phantom words\0"
	/*   287 */ "Red highlight\0"
	/*   301 */ "Tracking\0"
	/*   310 */ "Anchor\0"
	/*   317 */ "Guide width\0"
	/*   329 */ "Guide gap\0"
	/*   339 */ "Reset\0"
	/*   345 */ "Typography\0"
	/*   356 */ "tap to exit\0"
	/*   368 */ "tap to reset\0"
	/*   381 */ "Tap change  L/R sample\0"
	/*   404 */ "Tap exit  L/R sample\0"
	/*   425 */ "Tap toggle  L/R sample\0"
	/*   448 */ "Tap cycle  L/R sample\0"
	/*   470 */ "Current book\0"
	/*   483 */ "Start\0"
	/*   489 */ "Start of book\0"
	/*   503 */ "Restart book\0"
	/*   516 */ "Are you sure?\0"
	/*   530 */ "No, keep place\0"
	/*   545 */ "Yes, restart\0"
	/*   558 */ "No samples\0"
	/*   569 */ "Large\0"
	/*   575 */ "Medium\0"
	/*   582 */ "Small\0"
	/*   588 */ "Standard\0"
	/*   597 */ "RSVP\0"
	/*   602 */ "Page scroll\0"
	/*   614 */ "Time estimate\0"
	/*   628 */ "Accurate\0"
	/*   637 */ "Fast\0"
	/*   642 */ "Reanudar\0"
	/*   651 */ "Capitulos\0"
	/*   661 */ "Biblioteca\0"
	/*   672 */ "Ajustes\0"
	/*   680 */ "USB\0"
	/*   684 */ "Apagar\0"
	/*   691 */ "Atras\0"
	/*   697 */ "Pantalla\0"
	/*   706 */ "Tipografia\0"
	/*   717 */ "Ritmo lectura\0"
	/*   731 */ "Tema\0"
	/*   736 */ "Brillo\0"
	/*   743 */ "Idioma\0"
	/*   750 */ "Modo lectura\0"
	/*   763 */ "Palabras largas\0"
	/*   779 */ "Complejidad\0"
	/*   791 */ "Puntuacion\0"
	/*   802 */ "Restablecer ritmo\0"
	/*   820 */ "Noche\0"
	/*   826 */ "Oscuro\0"
	/*   833 */ "Claro\0"
	/*   839 */ "Si\0"
	/*   842 */ "No\0"
	/*   845 */ "Tamano\0"
	/*   852 */ "Fuente\0"
	/*   859 */ "Palabras fantasma\0"
	/*   877 */ "Rojo\0"
	/*   882 */ "Espaciado\0"
	/*   892 */ "Ancla\0"
	/*   898 */ "Ancho guia\0"
	/*   909 */ "Hueco guia\0"
	/*   920 */ "Restablecer\0"
	/*   932 */ "toca salir\0"
	/*   943 */ "toca reiniciar\0"
	/*   958 */ "Toca cambiar L/R muestra\0"
	/*   983 */ "Toca salir L/R muestra\0"
	/*  1006 */ "Toca alternar L/R muestra\0"
	/*  1032 */ "Toca ciclo L/R muestra\0"
	/*  1055 */ "Libro actual\0"
	/*  1068 */ "Inicio\0"
	/*  1075 */ "Inicio del libro\0"
	/*  1092 */ "Reiniciar libro\0"
	/*  1108 */ "Seguro?\0"
	/*  1116 */ "No, conservar\0"
	/*  1130 */ "Si, reiniciar\0"
	/*  1144 */ "Sin muestras\0"
	/*  1157 */ "Grande\0"
	/*  1164 */ "Mediano\0"
	/*  1172 */ "Pequeno\0"
	/*  1180 */ "Estandar\0"
	/*  1189 */ "Scroll pagina\0"
	/*  1203 */ "Tiempo restante\0"
	/*  1219 */ "Preciso\0"
	/*  1227 */ "Rapido\0"
	/*  1234 */ "Reprendre\0"
	/*  1244 */ "Chapitres\0"
	/*  1254 */ "Bibliotheque\0"
	/*  1267 */ "Reglages\0"
	/*  1276 */ "Eteindre\0"
	/*  1285 */ "Retour\0"
	/*  1292 */ "Affichage\0"
	/*  1302 */ "Typographie\0"
	/*  1314 */ "Rythme mots\0"
	/*  1326 */ "Luminosite\0"
	/*  1337 */ "Langue\0"
	/*  1344 */ "Mode lecture\0"
	/*  1357 */ "Mots longs\0"
	/*  1368 */ "Complexite\0"
	/*  1379 */ "Ponctuation\0"
	/*  1391 */ "Reinit. rythme\0"
	/*  1406 */ "Nuit\0"
	/*  1411 */ "Sombre\0"
	/*  1418 */ "Clair\0"
	/*  1424 */ "Oui\0"
	/*  1428 */ "Non\0"
	/*  1432 */ "Taille\0"
	/*  1439 */ "Police\0"
	/*  1446 */ "Mots fantomes\0"
	/*  1460 */ "Accent rouge\0"
	/*  1473 */ "Espacement\0"
	/*  1484 */ "Ancre\0"
	/*  1490 */ "Largeur guide\0"
	/*  1504 */ "Ecart guide\0"
	/*  1516 */ "Reinit.\0"
	/*  1524 */ "toucher sortie\0"
	/*  1539 */ "toucher reinit.\0"
	/*  1555 */ "Touchez change  G/D echant.\0"
	/*  1583 */ "Touchez sortie  G/D echant.\0"
	/*  1611 */ "Touchez option  G/D echant.\0"
	/*  1639 */ "Touchez cycle  G/D echant.\0"
	/*  1666 */ "Livre actuel\0"
	/*  1679 */ "Debut\0"
	/*  1685 */ "Debut du livre\0"
	/*  1700 */ "Relancer livre\0"
	/*  1715 */ "Confirmer ?\0"
	/*  1727 */ "Non, garder\0"
	/*  1739 */ "Oui, relancer\0"
	/*  1753 */ "Aucun exemple\0"
	/*  1767 */ "Grand\0"
	/*  1773 */ "Moyen\0"
	/*  1779 */ "Petit\0"
	/*  1785 */ "Defilement page\0"
	/*  1801 */ "Temps restant\0"
	/*  1815 */ "Precis\0"
	/*  1822 */ "Rapide\0"
	/*  1829 */ "Weiter\0"
	/*  1836 */ "Kapitel\0"
	/*  1844 */ "Bibliothek\0"
	/*  1855 */ "Optionen\0"
	/*  1864 */ "Ausschalten\0"
	/*  1876 */ "Zuruck\0"
	/*  1883 */ "Anzeige\0"
	/*  1891 */ "Typografie\0"
	/*  1902 */ "Lesetempo\0"
	/*  1912 */ "Thema\0"
	/*  1918 */ "Helligkeit\0"
	/*  1929 */ "Sprache\0"
	/*  1937 */ "Lesemodus\0"
	/*  1947 */ "Lange Worter\0"
	/*  1960 */ "Komplexitat\0"
	/*  1972 */ "Zeichen\0"
	/*  1980 */ "Tempo zuruck\0"
	/*  1993 */ "Nacht\0"
	/*  1999 */ "Dunkel\0"
	/*  2006 */ "Hell\0"
	/*  2011 */ "Ein\0"
	/*  2015 */ "Aus\0"
	/*  2019 */ "Schriftgrad\0"
	/*  2031 */ "Schriftart\0"
	/*  2042 */ "Phantomworter\0"
	/*  2056 */ "Rotfokus\0"
	/*  2065 */ "Laufweite\0"
	/*  2075 */ "Anker\0"
	/*  2081 */ "Guidebreite\0"
	/*  2093 */ "Guidespalt\0"
	/*  2104 */ "Zurucksetzen\0"
	/*  2117 */ "tippen zum Ende\0"
	/*  2133 */ "tippen zum Reset\0"
	/*  2150 */ "Tippen aendern  L/R Probe\0"
	/*  2176 */ "Tippen zuruck  L/R Probe\0"
	/*  2201 */ "Tippen schalten  L/R Probe\0"
	/*  2228 */ "Tippen wechseln  L/R Probe\0"
	/*  2255 */ "Aktuelles Buch\0"
	/*  2270 */ "Buchanfang\0"
	/*  2281 */ "Buch neu\0"
	/*  2290 */ "Sicher?\0"
	/*  2298 */ "Nein, merken\0"
	/*  2311 */ "Ja, neu\0"
	/*  2319 */ "Keine Proben\0"
	/*  2332 */ "Gross\0"
	/*  2338 */ "Mittel\0"
	/*  2345 */ "Klein\0"
	/*  2351 */ "Seiten-Scroll\0"
	/*  2365 */ "Restzeit\0"
	/*  2374 */ "Genau\0"
	/*  2380 */ "Schnell\0"
	/*  2388 */ "Continua\0"
	/*  2397 */ "Capitole\0"
	/*  2406 */ "Setari\0"
	/*  2413 */ "Oprire\0"
	/*  2420 */ "Inapoi\0"
	/*  2427 */ "Afisaj\0"
	/*  2434 */ "Tipografie\0"
	/*  2445 */ "Ritm cuvinte\0"
	/*  2458 */ "Luminoz.\0"
	/*  2467 */ "Limba\0"
	/*  2473 */ "Mod citire\0"
	/*  2484 */ "Cuvinte lungi\0"
	/*  2498 */ "Complexitate\0"
	/*  2511 */ "Punctuatie\0"
	/*  2522 */ "Reset ritm\0"
	/*  2533 */ "Noapte\0"
	/*  2540 */ "Inchis\0"
	/*  2547 */ "Deschis\0"
	/*  2555 */ "Pornit\0"
	/*  2562 */ "Oprit\0"
	/*  2568 */ "Marime\0"
	/*  2575 */ "Font\0"
	/*  2580 */ "Cuvinte fantoma\0"
	/*  2596 */ "Accent rosu\0"
	/*  2608 */ "Spatiere\0"
	/*  2617 */ "Ancora\0"
	/*  2624 */ "Latime ghid\0"
	/*  2636 */ "Spatiu ghid\0"
	/*  2648 */ "Resetare\0"
	/*  2657 */ "atinge iesire\0"
	/*  2671 */ "atinge reset\0"
	/*  2684 */ "Atinge schimba  S/D proba\0"
	/*  2710 */ "Atinge iesi  S/D proba\0"
	/*  2733 */ "Atinge comuta  S/D proba\0"
	/*  2758 */ "Atinge ciclu  S/D proba\0"
	/*  2782 */ "Cartea curenta\0"
	/*  2797 */ "Inceput\0"
	/*  2805 */ "Inceputul cartii\0"
	/*  2822 */ "Reporneste cartea\0"
	/*  2840 */ "Sigur?\0"
	/*  2847 */ "Nu, pastreaza\0"
	/*  2861 */ "Da, reporneste\0"
	/*  2876 */ "Fara probe\0"
	/*  2887 */ "Mare\0"
	/*  2892 */ "Mediu\0"
	/*  2898 */ "Mic\0"
	/*  2902 */ "Derulare pagina\0"
	/*  2918 */ "Timp ramas\0"
	/*  2929 */ "Exact\0"
	/*  2935 */ "Rapid\0"
	/*  2941 */ "Wznow\0"
	/*  2947 */ "Rozdzialy\0"
	/*  2957 */ "Biblioteka\0"
	/*  2968 */ "Ustawienia\0"
	/*  2979 */ "Wylacz\0"
	/*  2986 */ "Wroc\0"
	/*  2991 */ "Ekran\0"
	/*  2997 */ "Typografia\0"
	/*  3008 */ "Tempo slow\0"
	/*  3019 */ "Motyw\0"
	/*  3025 */ "Jasnosc\0"
	/*  3033 */ "Jezyk\0"
	/*  3039 */ "Tryb czyt.\0"
	/*  3050 */ "Dlugie slowa\0"
	/*  3063 */ "Zlozonosc\0"
	/*  3073 */ "Interpunk.\0"
	/*  3084 */ "Reset tempa\0"
	/*  3096 */ "Noc\0"
	/*  3100 */ "Ciemny\0"
	/*  3107 */ "Jasny\0"
	/*  3113 */ "Tak\0"
	/*  3117 */ "Nie\0"
	/*  3121 */ "Rozmiar\0"
	/*  3129 */ "Kroj\0"
	/*  3134 */ "Slowa widma\0"
	/*  3146 */ "Czerwony\0"
	/*  3155 */ "Odstepy\0"
	/*  3163 */ "Kotwica\0"
	/*  3171 */ "Szer. guide\0"
	/*  3183 */ "Przerwa guide\0"
	/*  3197 */ "dotknij wyjscie\0"
	/*  3213 */ "dotknij reset\0"
	/*  3227 */ "Dotknij zmien  L/R probka\0"
	/*  3253 */ "Dotknij wyjdz  L/R probka\0"
	/*  3279 */ "Dotknij przel.  L/R probka\0"
	/*  3306 */ "Dotknij cykl  L/R probka\0"
	/*  3331 */ "Biezaca ksiazka\0"
	/*  3347 */ "Poczatek ksiazki\0"
	/*  3364 */ "Restart ksiazki\0"
	/*  3380 */ "Na pewno?\0"
	/*  3390 */ "Nie, zostaw\0"
	/*  3402 */ "Tak, restart\0"
	/*  3415 */ "Brak probek\0"
	/*  3427 */ "Duzy\0"
	/*  3432 */ "Sredni\0"
	/*  3439 */ "Maly\0"
	/*  3444 */ "Scroll strony\0"
	/*  3458 */ "Pozostaly czas\0"
	/*  3473 */ "Dokladny\0"
	/*  3482 */ "Szybki\0";

constexpr std::array<uint16_t, kLanguageCount> kLanguageNameOffsets = {{
	/* English  */ 0,
	/* Spanish  */ 8,
	/* French   */ 16,
	/* German   */ 25,
	/* Romanian */ 33,
	/* Polish   */ 40,
}};

using TextOffsetRow = std::array<uint16_t, kTextCount>;
using TextOffsetTable = std::array<TextOffsetRow, kLanguageCount>;

constexpr TextOffsetTable kTextOffsets = {{
	// English (en)
	{{
		/* Resume                   */ 47,
		/* Chapters                 */ 54,
		/* Library                  */ 63,
		/* Settings                 */ 71,
		/* UsbTransfer              */ 80,
		/* PowerOff                 */ 93,
		/* Back                     */ 103,
		/* Display                  */ 108,
		/* TypographyTune           */ 116,
		/* WordPacing               */ 132,
		/* Theme                    */ 144,
		/* Brightness               */ 150,
		/* Language                 */ 161,
		/* ReadingMode              */ 170,
		/* LongWords                */ 183,
		/* Complexity               */ 194,
		/* Punctuation              */ 205,
		/* ResetPacing              */ 217,
		/* Night                    */ 230,
		/* Dark                     */ 236,
		/* Light                    */ 241,
		/* On                       */ 247,
		/* Off                      */ 250,
		/* FontSize                 */ 254,
		/* Typeface                 */ 264,
		/* PhantomWords             */ 273,
		/* RedHighlight             */ 287,
		/* Tracking                 */ 301,
		/* Anchor                   */ 310,
		/* GuideWidth               */ 317,
		/* GuideGap                 */ 329,
		/* Reset                    */ 339,
		/* Typography               */ 345,
		/* TapToExit                */ 356,
		/* TapToReset               */ 368,
		/* TapChangeSample          */ 381,
		/* TapExitSample            */ 404,
		/* TapToggleSample          */ 425,
		/* TapCycleSample           */ 448,
		/* CurrentBook              */ 470,
		/* Start                    */ 483,
		/* StartOfBook              */ 489,
		/* RestartBook              */ 503,
		/* AreYouSure               */ 516,
		/* NoKeepPlace              */ 530,
		/* YesRestart               */ 545,
		/* NoSamples                */ 558,
		/* Large                    */ 569,
		/* Medium                   */ 575,
		/* Small                    */ 582,
		/* Standard                 */ 588,
		/* RsvpMode                 */ 597,
		/* ScrollMode               */ 602,
		/* TimeEstimate             */ 614,
		/* TimeEstimateAccurate     */ 628,
		/* TimeEstimateFast         */ 637,
	}},
	// Spanish (es)
	{{
		/* Resume                   */ 642,
		/* Chapters                 */ 651,
		/* Library                  */ 661,
		/* Settings                 */ 672,
		/* UsbTransfer              */ 680,
		/* PowerOff                 */ 684,
		/* Back                     */ 691,
		/* Display                  */ 697,
		/* TypographyTune           */ 706,
		/* WordPacing               */ 717,
		/* Theme                    */ 731,
		/* Brightness               */ 736,
		/* Language                 */ 743,
		/* ReadingMode              */ 750,
		/* LongWords                */ 763,
		/* Complexity               */ 779,
		/* Punctuation              */ 791,
		/* ResetPacing              */ 802,
		/* Night                    */ 820,
		/* Dark                     */ 826,
		/* Light                    */ 833,
		/* On                       */ 839,
		/* Off                      */ 842,
		/* FontSize                 */ 845,
		/* Typeface                 */ 852,
		/* PhantomWords             */ 859,
		/* RedHighlight             */ 877,
		/* Tracking                 */ 882,
		/* Anchor                   */ 892,
		/* GuideWidth               */ 898,
		/* GuideGap                 */ 909,
		/* Reset                    */ 920,
		/* Typography               */ 706,
		/* TapToExit                */ 932,
		/* TapToReset               */ 943,
		/* TapChangeSample          */ 958,
		/* TapExitSample            */ 983,
		/* TapToggleSample          */ 1006,
		/* TapCycleSample           */ 1032,
		/* CurrentBook              */ 1055,
		/* Start                    */ 1068,
		/* StartOfBook              */ 1075,
		/* RestartBook              */ 1092,
		/* AreYouSure               */ 1108,
		/* NoKeepPlace              */ 1116,
		/* YesRestart               */ 1130,
		/* NoSamples                */ 1144,
		/* Large                    */ 1157,
		/* Medium                   */ 1164,
		/* Small                    */ 1172,
		/* Standard                 */ 1180,
		/* RsvpMode                 */ 597,
		/* ScrollMode               */ 1189,
		/* TimeEstimate             */ 1203,
		/* TimeEstimateAccurate     */ 1219,
		/* TimeEstimateFast         */ 1227,
	}},
	// French (fr)
	{{
		/* Resume                   */ 1234,
		/* Chapters                 */ 1244,
		/* Library                  */ 1254,
		/* Settings                 */ 1267,
		/* UsbTransfer              */ 680,
		/* PowerOff                 */ 1276,
		/* Back                     */ 1285,
		/* Display                  */ 1292,
		/* TypographyTune           */ 1302,
		/* WordPacing               */ 1314,
		/* Theme                    */ 144,
		/* Brightness               */ 1326,
		/* Language                 */ 1337,
		/* ReadingMode              */ 1344,
		/* LongWords                */ 1357,
		/* Complexity               */ 1368,
		/* Punctuation              */ 1379,
		/* ResetPacing              */ 1391,
		/* Night                    */ 1406,
		/* Dark                     */ 1411,
		/* Light                    */ 1418,
		/* On                       */ 1424,
		/* Off                      */ 1428,
		/* FontSize                 */ 1432,
		/* Typeface                 */ 1439,
		/* PhantomWords             */ 1446,
		/* RedHighlight             */ 1460,
		/* Tracking                 */ 1473,
		/* Anchor                   */ 1484,
		/* GuideWidth               */ 1490,
		/* GuideGap                 */ 1504,
		/* Reset                    */ 1516,
		/* Typography               */ 1302,
		/* TapToExit                */ 1524,
		/* TapToReset               */ 1539,
		/* TapChangeSample          */ 1555,
		/* TapExitSample            */ 1583,
		/* TapToggleSample          */ 1611,
		/* TapCycleSample           */ 1639,
		/* CurrentBook              */ 1666,
		/* Start                    */ 1679,
		/* StartOfBook              */ 1685,
		/* RestartBook              */ 1700,
		/* AreYouSure               */ 1715,
		/* NoKeepPlace              */ 1727,
		/* YesRestart               */ 1739,
		/* NoSamples                */ 1753,
		/* Large                    */ 1767,
		/* Medium                   */ 1773,
		/* Small                    */ 1779,
		/* Standard                 */ 588,
		/* RsvpMode                 */ 597,
		/* ScrollMode               */ 1785,
		/* TimeEstimate             */ 1801,
		/* TimeEstimateAccurate     */ 1815,
		/* TimeEstimateFast         */ 1822,
	}},
	// German (de)
	{{
		/* Resume                   */ 1829,
		/* Chapters                 */ 1836,
		/* Library                  */ 1844,
		/* Settings                 */ 1855,
		/* UsbTransfer              */ 680,
		/* PowerOff                 */ 1864,
		/* Back                     */ 1876,
		/* Display                  */ 1883,
		/* TypographyTune           */ 1891,
		/* WordPacing               */ 1902,
		/* Theme                    */ 1912,
		/* Brightness               */ 1918,
		/* Language                 */ 1929,
		/* ReadingMode              */ 1937,
		/* LongWords                */ 1947,
		/* Complexity               */ 1960,
		/* Punctuation              */ 1972,
		/* ResetPacing              */ 1980,
		/* Night                    */ 1993,
		/* Dark                     */ 1999,
		/* Light                    */ 2006,
		/* On                       */ 2011,
		/* Off                      */ 2015,
		/* FontSize                 */ 2019,
		/* Typeface                 */ 2031,
		/* PhantomWords             */ 2042,
		/* RedHighlight             */ 2056,
		/* Tracking                 */ 2065,
		/* Anchor                   */ 2075,
		/* GuideWidth               */ 2081,
		/* GuideGap                 */ 2093,
		/* Reset                    */ 2104,
		/* Typography               */ 1891,
		/* TapToExit                */ 2117,
		/* TapToReset               */ 2133,
		/* TapChangeSample          */ 2150,
		/* TapExitSample            */ 2176,
		/* TapToggleSample          */ 2201,
		/* TapCycleSample           */ 2228,
		/* CurrentBook              */ 2255,
		/* Start                    */ 483,
		/* StartOfBook              */ 2270,
		/* RestartBook              */ 2281,
		/* AreYouSure               */ 2290,
		/* NoKeepPlace              */ 2298,
		/* YesRestart               */ 2311,
		/* NoSamples                */ 2319,
		/* Large                    */ 2332,
		/* Medium                   */ 2338,
		/* Small                    */ 2345,
		/* Standard                 */ 588,
		/* RsvpMode                 */ 597,
		/* ScrollMode               */ 2351,
		/* TimeEstimate             */ 2365,
		/* TimeEstimateAccurate     */ 2374,
		/* TimeEstimateFast         */ 2380,
	}},
	// Romanian (ro)
	{{
		/* Resume                   */ 2388,
		/* Chapters                 */ 2397,
		/* Library                  */ 661,
		/* Settings                 */ 2406,
		/* UsbTransfer              */ 680,
		/* PowerOff                 */ 2413,
		/* Back                     */ 2420,
		/* Display                  */ 2427,
		/* TypographyTune           */ 2434,
		/* WordPacing               */ 2445,
		/* Theme                    */ 731,
		/* Brightness               */ 2458,
		/* Language                 */ 2467,
		/* ReadingMode              */ 2473,
		/* LongWords                */ 2484,
		/* Complexity               */ 2498,
		/* Punctuation              */ 2511,
		/* ResetPacing              */ 2522,
		/* Night                    */ 2533,
		/* Dark                     */ 2540,
		/* Light                    */ 2547,
		/* On                       */ 2555,
		/* Off                      */ 2562,
		/* FontSize                 */ 2568,
		/* Typeface                 */ 2575,
		/* PhantomWords             */ 2580,
		/* RedHighlight             */ 2596,
		/* Tracking                 */ 2608,
		/* Anchor                   */ 2617,
		/* GuideWidth               */ 2624,
		/* GuideGap                 */ 2636,
		/* Reset                    */ 2648,
		/* Typography               */ 2434,
		/* TapToExit                */ 2657,
		/* TapToReset               */ 2671,
		/* TapChangeSample          */ 2684,
		/* TapExitSample            */ 2710,
		/* TapToggleSample          */ 2733,
		/* TapCycleSample           */ 2758,
		/* CurrentBook              */ 2782,
		/* Start                    */ 2797,
		/* StartOfBook              */ 2805,
		/* RestartBook              */ 2822,
		/* AreYouSure               */ 2840,
		/* NoKeepPlace              */ 2847,
		/* YesRestart               */ 2861,
		/* NoSamples                */ 2876,
		/* Large                    */ 2887,
		/* Medium                   */ 2892,
		/* Small                    */ 2898,
		/* Standard                 */ 588,
		/* RsvpMode                 */ 597,
		/* ScrollMode               */ 2902,
		/* TimeEstimate             */ 2918,
		/* TimeEstimateAccurate     */ 2929,
		/* TimeEstimateFast         */ 2935,
	}},
	// Polish (pl)
	{{
		/* Resume                   */ 2941,
		/* Chapters                 */ 2947,
		/* Library                  */ 2957,
		/* Settings                 */ 2968,
		/* UsbTransfer              */ 680,
		/* PowerOff                 */ 2979,
		/* Back                     */ 2986,
		/* Display                  */ 2991,
		/* TypographyTune           */ 2997,
		/* WordPacing               */ 3008,
		/* Theme                    */ 3019,
		/* Brightness               */ 3025,
		/* Language                 */ 3033,
		/* ReadingMode              */ 3039,
		/* LongWords                */ 3050,
		/* Complexity               */ 3063,
		/* Punctuation              */ 3073,
		/* ResetPacing              */ 3084,
		/* Night                    */ 3096,
		/* Dark                     */ 3100,
		/* Light                    */ 3107,
		/* On                       */ 3113,
		/* Off                      */ 3117,
		/* FontSize                 */ 3121,
		/* Typeface                 */ 3129,
		/* PhantomWords             */ 3134,
		/* RedHighlight             */ 3146,
		/* Tracking                 */ 3155,
		/* Anchor                   */ 3163,
		/* GuideWidth               */ 3171,
		/* GuideGap                 */ 3183,
		/* Reset                    */ 339,
		/* Typography               */ 2997,
		/* TapToExit                */ 3197,
		/* TapToReset               */ 3213,
		/* TapChangeSample          */ 3227,
		/* TapExitSample            */ 3253,
		/* TapToggleSample          */ 3279,
		/* TapCycleSample           */ 3306,
		/* CurrentBook              */ 3331,
		/* Start                    */ 483,
		/* StartOfBook              */ 3347,
		/* RestartBook              */ 3364,
		/* AreYouSure               */ 3380,
		/* NoKeepPlace              */ 3390,
		/* YesRestart               */ 3402,
		/* NoSamples                */ 3415,
		/* Large                    */ 3427,
		/* Medium                   */ 3432,
		/* Small                    */ 3439,
		/* Standard                 */ 588,
		/* RsvpMode                 */ 597,
		/* ScrollMode               */ 3444,
		/* TimeEstimate             */ 3458,
		/* TimeEstimateAccurate     */ 3473,
		/* TimeEstimateFast         */ 3482,
	}},
}};

size_t languageIndex(UiLanguage language) {
	const size_t value = static_cast<size_t>(language);
	return value < kLanguageCount ? value : kDefaultLanguageIndex;
}

}  // namespace

namespace Localization {

UiLanguage sanitizeLanguage(uint8_t value) {
	if (value >= kLanguageCount) {
		return static_cast<UiLanguage>(kDefaultLanguageIndex);
	}
	return static_cast<UiLanguage>(value);
}

UiLanguage nextLanguage(UiLanguage current) {
	const size_t value = languageIndex(current);
	return static_cast<UiLanguage>((value + 1) % kLanguageCount);
}

const char *languageName(UiLanguage language) {
	return &kStringBlob[kLanguageNameOffsets[languageIndex(language)]];
}

const char *text(UiLanguage language, UiText key) {
	const size_t textIndex = static_cast<size_t>(key);
	if (textIndex >= kTextCount) {
		return "";
	}

	const size_t lang = languageIndex(language);
	uint16_t offset = kTextOffsets[lang][textIndex];

	if (offset == kMissingOffset) {
		offset = kTextOffsets[kDefaultLanguageIndex][textIndex];
	}

	return offset == kMissingOffset ? "" : &kStringBlob[offset];
}

}  // namespace Localization
