// Generated by tools/generate_localization.py. Do not edit by hand.
// Edit localization/strings.toml, then run the generator.
#include "Localization.h"

#include <array>
#include <cstddef>

namespace {

constexpr size_t kLanguageCount = static_cast<size_t>(UiLanguage::Count);
constexpr size_t kTextCount = static_cast<size_t>(UiText::Count);
constexpr size_t kDefaultLanguageIndex = 0;
constexpr uint16_t kMissingOffset = 0xFFFF;

static_assert(kLanguageCount == 7, "UiLanguage count mismatch");
static_assert(kTextCount == 56, "UiText count mismatch");

constexpr char kStringBlob[] =
	/*     0 */ "English\0"
	/*     8 */ "Espanol\0"
	/*    16 */ "Francais\0"
	/*    25 */ "Deutsch\0"
	/*    33 */ "Romana\0"
	/*    40 */ "Polski\0"
	/*    47 */ "\u0420\u0443\u0441\u0441\u043A\u0438\u0439\0"
	/*    62 */ "Resume\0"
	/*    69 */ "Chapters\0"
	/*    78 */ "Library\0"
	/*    86 */ "Settings\0"
	/*    95 */ "USB transfer\0"
	/*   108 */ "Power off\0"
	/*   118 */ "Back\0"
	/*   123 */ "Display\0"
	/*   131 */ "Typography tune\0"
	/*   147 */ "Word pacing\0"
	/*   159 */ "Theme\0"
	/*   165 */ "Brightness\0"
	/*   176 */ "Language\0"
	/*   185 */ "Reading mode\0"
	/*   198 */ "Long words\0"
	/*   209 */ "Complexity\0"
	/*   220 */ "Punctuation\0"
	/*   232 */ "Reset pacing\0"
	/*   245 */ "Night\0"
	/*   251 */ "Dark\0"
	/*   256 */ "Light\0"
	/*   262 */ "On\0"
	/*   265 */ "Off\0"
	/*   269 */ "Font size\0"
	/*   279 */ "Typeface\0"
	/*   288 */ "Phantom words\0"
	/*   302 */ "Red highlight\0"
	/*   316 */ "Tracking\0"
	/*   325 */ "Anchor\0"
	/*   332 */ "Guide width\0"
	/*   344 */ "Guide gap\0"
	/*   354 */ "Reset\0"
	/*   360 */ "Typography\0"
	/*   371 */ "tap to exit\0"
	/*   383 */ "tap to reset\0"
	/*   396 */ "Tap change  L/R sample\0"
	/*   419 */ "Tap exit  L/R sample\0"
	/*   440 */ "Tap toggle  L/R sample\0"
	/*   463 */ "Tap cycle  L/R sample\0"
	/*   485 */ "Current book\0"
	/*   498 */ "Start\0"
	/*   504 */ "Start of book\0"
	/*   518 */ "Restart book\0"
	/*   531 */ "Are you sure?\0"
	/*   545 */ "No, keep place\0"
	/*   560 */ "Yes, restart\0"
	/*   573 */ "No samples\0"
	/*   584 */ "Large\0"
	/*   590 */ "Medium\0"
	/*   597 */ "Small\0"
	/*   603 */ "Standard\0"
	/*   612 */ "RSVP\0"
	/*   617 */ "Page scroll\0"
	/*   629 */ "Time estimate\0"
	/*   643 */ "Accurate\0"
	/*   652 */ "Fast\0"
	/*   657 */ "Reanudar\0"
	/*   666 */ "Capitulos\0"
	/*   676 */ "Biblioteca\0"
	/*   687 */ "Ajustes\0"
	/*   695 */ "USB\0"
	/*   699 */ "Apagar\0"
	/*   706 */ "Atras\0"
	/*   712 */ "Pantalla\0"
	/*   721 */ "Tipografia\0"
	/*   732 */ "Ritmo lectura\0"
	/*   746 */ "Tema\0"
	/*   751 */ "Brillo\0"
	/*   758 */ "Idioma\0"
	/*   765 */ "Modo lectura\0"
	/*   778 */ "Palabras largas\0"
	/*   794 */ "Complejidad\0"
	/*   806 */ "Puntuacion\0"
	/*   817 */ "Restablecer ritmo\0"
	/*   835 */ "Noche\0"
	/*   841 */ "Oscuro\0"
	/*   848 */ "Claro\0"
	/*   854 */ "Si\0"
	/*   857 */ "No\0"
	/*   860 */ "Tamano\0"
	/*   867 */ "Fuente\0"
	/*   874 */ "Palabras fantasma\0"
	/*   892 */ "Rojo\0"
	/*   897 */ "Espaciado\0"
	/*   907 */ "Ancla\0"
	/*   913 */ "Ancho guia\0"
	/*   924 */ "Hueco guia\0"
	/*   935 */ "Restablecer\0"
	/*   947 */ "toca salir\0"
	/*   958 */ "toca reiniciar\0"
	/*   973 */ "Toca cambiar L/R muestra\0"
	/*   998 */ "Toca salir L/R muestra\0"
	/*  1021 */ "Toca alternar L/R muestra\0"
	/*  1047 */ "Toca ciclo L/R muestra\0"
	/*  1070 */ "Libro actual\0"
	/*  1083 */ "Inicio\0"
	/*  1090 */ "Inicio del libro\0"
	/*  1107 */ "Reiniciar libro\0"
	/*  1123 */ "Seguro?\0"
	/*  1131 */ "No, conservar\0"
	/*  1145 */ "Si, reiniciar\0"
	/*  1159 */ "Sin muestras\0"
	/*  1172 */ "Grande\0"
	/*  1179 */ "Mediano\0"
	/*  1187 */ "Pequeno\0"
	/*  1195 */ "Estandar\0"
	/*  1204 */ "Scroll pagina\0"
	/*  1218 */ "Tiempo restante\0"
	/*  1234 */ "Preciso\0"
	/*  1242 */ "Rapido\0"
	/*  1249 */ "Reprendre\0"
	/*  1259 */ "Chapitres\0"
	/*  1269 */ "Bibliotheque\0"
	/*  1282 */ "Reglages\0"
	/*  1291 */ "Eteindre\0"
	/*  1300 */ "Retour\0"
	/*  1307 */ "Affichage\0"
	/*  1317 */ "Typographie\0"
	/*  1329 */ "Rythme mots\0"
	/*  1341 */ "Luminosite\0"
	/*  1352 */ "Langue\0"
	/*  1359 */ "Mode lecture\0"
	/*  1372 */ "Mots longs\0"
	/*  1383 */ "Complexite\0"
	/*  1394 */ "Ponctuation\0"
	/*  1406 */ "Reinit. rythme\0"
	/*  1421 */ "Nuit\0"
	/*  1426 */ "Sombre\0"
	/*  1433 */ "Clair\0"
	/*  1439 */ "Oui\0"
	/*  1443 */ "Non\0"
	/*  1447 */ "Taille\0"
	/*  1454 */ "Police\0"
	/*  1461 */ "Mots fantomes\0"
	/*  1475 */ "Accent rouge\0"
	/*  1488 */ "Espacement\0"
	/*  1499 */ "Ancre\0"
	/*  1505 */ "Largeur guide\0"
	/*  1519 */ "Ecart guide\0"
	/*  1531 */ "Reinit.\0"
	/*  1539 */ "toucher sortie\0"
	/*  1554 */ "toucher reinit.\0"
	/*  1570 */ "Touchez change  G/D echant.\0"
	/*  1598 */ "Touchez sortie  G/D echant.\0"
	/*  1626 */ "Touchez option  G/D echant.\0"
	/*  1654 */ "Touchez cycle  G/D echant.\0"
	/*  1681 */ "Livre actuel\0"
	/*  1694 */ "Debut\0"
	/*  1700 */ "Debut du livre\0"
	/*  1715 */ "Relancer livre\0"
	/*  1730 */ "Confirmer ?\0"
	/*  1742 */ "Non, garder\0"
	/*  1754 */ "Oui, relancer\0"
	/*  1768 */ "Aucun exemple\0"
	/*  1782 */ "Grand\0"
	/*  1788 */ "Moyen\0"
	/*  1794 */ "Petit\0"
	/*  1800 */ "Defilement page\0"
	/*  1816 */ "Temps restant\0"
	/*  1830 */ "Precis\0"
	/*  1837 */ "Rapide\0"
	/*  1844 */ "Weiter\0"
	/*  1851 */ "Kapitel\0"
	/*  1859 */ "Bibliothek\0"
	/*  1870 */ "Optionen\0"
	/*  1879 */ "Ausschalten\0"
	/*  1891 */ "Zuruck\0"
	/*  1898 */ "Anzeige\0"
	/*  1906 */ "Typografie\0"
	/*  1917 */ "Lesetempo\0"
	/*  1927 */ "Thema\0"
	/*  1933 */ "Helligkeit\0"
	/*  1944 */ "Sprache\0"
	/*  1952 */ "Lesemodus\0"
	/*  1962 */ "Lange Worter\0"
	/*  1975 */ "Komplexitat\0"
	/*  1987 */ "Zeichen\0"
	/*  1995 */ "Tempo zuruck\0"
	/*  2008 */ "Nacht\0"
	/*  2014 */ "Dunkel\0"
	/*  2021 */ "Hell\0"
	/*  2026 */ "Ein\0"
	/*  2030 */ "Aus\0"
	/*  2034 */ "Schriftgrad\0"
	/*  2046 */ "Schriftart\0"
	/*  2057 */ "Phantomworter\0"
	/*  2071 */ "Rotfokus\0"
	/*  2080 */ "Laufweite\0"
	/*  2090 */ "Anker\0"
	/*  2096 */ "Guidebreite\0"
	/*  2108 */ "Guidespalt\0"
	/*  2119 */ "Zurucksetzen\0"
	/*  2132 */ "tippen zum Ende\0"
	/*  2148 */ "tippen zum Reset\0"
	/*  2165 */ "Tippen aendern  L/R Probe\0"
	/*  2191 */ "Tippen zuruck  L/R Probe\0"
	/*  2216 */ "Tippen schalten  L/R Probe\0"
	/*  2243 */ "Tippen wechseln  L/R Probe\0"
	/*  2270 */ "Aktuelles Buch\0"
	/*  2285 */ "Buchanfang\0"
	/*  2296 */ "Buch neu\0"
	/*  2305 */ "Sicher?\0"
	/*  2313 */ "Nein, merken\0"
	/*  2326 */ "Ja, neu\0"
	/*  2334 */ "Keine Proben\0"
	/*  2347 */ "Gross\0"
	/*  2353 */ "Mittel\0"
	/*  2360 */ "Klein\0"
	/*  2366 */ "Seiten-Scroll\0"
	/*  2380 */ "Restzeit\0"
	/*  2389 */ "Genau\0"
	/*  2395 */ "Schnell\0"
	/*  2403 */ "Continua\0"
	/*  2412 */ "Capitole\0"
	/*  2421 */ "Setari\0"
	/*  2428 */ "Oprire\0"
	/*  2435 */ "Inapoi\0"
	/*  2442 */ "Afisaj\0"
	/*  2449 */ "Tipografie\0"
	/*  2460 */ "Ritm cuvinte\0"
	/*  2473 */ "Luminoz.\0"
	/*  2482 */ "Limba\0"
	/*  2488 */ "Mod citire\0"
	/*  2499 */ "Cuvinte lungi\0"
	/*  2513 */ "Complexitate\0"
	/*  2526 */ "Punctuatie\0"
	/*  2537 */ "Reset ritm\0"
	/*  2548 */ "Noapte\0"
	/*  2555 */ "Inchis\0"
	/*  2562 */ "Deschis\0"
	/*  2570 */ "Pornit\0"
	/*  2577 */ "Oprit\0"
	/*  2583 */ "Marime\0"
	/*  2590 */ "Font\0"
	/*  2595 */ "Cuvinte fantoma\0"
	/*  2611 */ "Accent rosu\0"
	/*  2623 */ "Spatiere\0"
	/*  2632 */ "Ancora\0"
	/*  2639 */ "Latime ghid\0"
	/*  2651 */ "Spatiu ghid\0"
	/*  2663 */ "Resetare\0"
	/*  2672 */ "atinge iesire\0"
	/*  2686 */ "atinge reset\0"
	/*  2699 */ "Atinge schimba  S/D proba\0"
	/*  2725 */ "Atinge iesi  S/D proba\0"
	/*  2748 */ "Atinge comuta  S/D proba\0"
	/*  2773 */ "Atinge ciclu  S/D proba\0"
	/*  2797 */ "Cartea curenta\0"
	/*  2812 */ "Inceput\0"
	/*  2820 */ "Inceputul cartii\0"
	/*  2837 */ "Reporneste cartea\0"
	/*  2855 */ "Sigur?\0"
	/*  2862 */ "Nu, pastreaza\0"
	/*  2876 */ "Da, reporneste\0"
	/*  2891 */ "Fara probe\0"
	/*  2902 */ "Mare\0"
	/*  2907 */ "Mediu\0"
	/*  2913 */ "Mic\0"
	/*  2917 */ "Derulare pagina\0"
	/*  2933 */ "Timp ramas\0"
	/*  2944 */ "Exact\0"
	/*  2950 */ "Rapid\0"
	/*  2956 */ "Wznow\0"
	/*  2962 */ "Rozdzialy\0"
	/*  2972 */ "Biblioteka\0"
	/*  2983 */ "Ustawienia\0"
	/*  2994 */ "Wylacz\0"
	/*  3001 */ "Wroc\0"
	/*  3006 */ "Ekran\0"
	/*  3012 */ "Typografia\0"
	/*  3023 */ "Tempo slow\0"
	/*  3034 */ "Motyw\0"
	/*  3040 */ "Jasnosc\0"
	/*  3048 */ "Jezyk\0"
	/*  3054 */ "Tryb czyt.\0"
	/*  3065 */ "Dlugie slowa\0"
	/*  3078 */ "Zlozonosc\0"
	/*  3088 */ "Interpunk.\0"
	/*  3099 */ "Reset tempa\0"
	/*  3111 */ "Noc\0"
	/*  3115 */ "Ciemny\0"
	/*  3122 */ "Jasny\0"
	/*  3128 */ "Tak\0"
	/*  3132 */ "Nie\0"
	/*  3136 */ "Rozmiar\0"
	/*  3144 */ "Kroj\0"
	/*  3149 */ "Slowa widma\0"
	/*  3161 */ "Czerwony\0"
	/*  3170 */ "Odstepy\0"
	/*  3178 */ "Kotwica\0"
	/*  3186 */ "Szer. guide\0"
	/*  3198 */ "Przerwa guide\0"
	/*  3212 */ "dotknij wyjscie\0"
	/*  3228 */ "dotknij reset\0"
	/*  3242 */ "Dotknij zmien  L/R probka\0"
	/*  3268 */ "Dotknij wyjdz  L/R probka\0"
	/*  3294 */ "Dotknij przel.  L/R probka\0"
	/*  3321 */ "Dotknij cykl  L/R probka\0"
	/*  3346 */ "Biezaca ksiazka\0"
	/*  3362 */ "Poczatek ksiazki\0"
	/*  3379 */ "Restart ksiazki\0"
	/*  3395 */ "Na pewno?\0"
	/*  3405 */ "Nie, zostaw\0"
	/*  3417 */ "Tak, restart\0"
	/*  3430 */ "Brak probek\0"
	/*  3442 */ "Duzy\0"
	/*  3447 */ "Sredni\0"
	/*  3454 */ "Maly\0"
	/*  3459 */ "Scroll strony\0"
	/*  3473 */ "Pozostaly czas\0"
	/*  3488 */ "Dokladny\0"
	/*  3497 */ "Szybki\0"
	/*  3504 */ "\u041F\u0440\u043E\u0434\u043E\u043B\u0436\u0438\u0442\u044C\0"
	/*  3525 */ "\u0413\u043B\u0430\u0432\u044B\0"
	/*  3536 */ "\u0411\u0438\u0431\u043B\u0438\u043E\u0442\u0435\u043A\u0430\0"
	/*  3557 */ "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438\0"
	/*  3576 */ "\u0412\u044B\u043A\u043B\u044E\u0447\u0438\u0442\u044C\0"
	/*  3595 */ "\u041D\u0430\u0437\u0430\u0434\0"
	/*  3606 */ "\u042D\u043A\u0440\u0430\u043D\0"
	/*  3617 */ "\u0422\u0438\u043F\u043E\u0433\u0440\u0430\u0444\u0438\u043A\u0430\0"
	/*  3640 */ "\u0422\u0435\u043C\u043F \u0441\u043B\u043E\u0432\0"
	/*  3658 */ "\u0422\u0435\u043C\u0430\0"
	/*  3667 */ "\u042F\u0440\u043A\u043E\u0441\u0442\u044C\0"
	/*  3682 */ "\u042F\u0437\u044B\u043A\0"
	/*  3691 */ "\u0420\u0435\u0436\u0438\u043C \u0447\u0442\u0435\u043D\u0438\u044F\0"
	/*  3715 */ "\u0414\u043B\u0438\u043D\u043D\u044B\u0435 \u0441\u043B\u043E\u0432\u0430\0"
	/*  3741 */ "\u0421\u043B\u043E\u0436\u043D\u043E\u0441\u0442\u044C\0"
	/*  3760 */ "\u041F\u0443\u043D\u043A\u0442\u0443\u0430\u0446\u0438\u044F\0"
	/*  3781 */ "\u0421\u0431\u0440\u043E\u0441 \u0442\u0435\u043C\u043F\u0430\0"
	/*  3803 */ "\u041D\u043E\u0447\u044C\0"
	/*  3812 */ "\u0422\u0451\u043C\u043D\u0430\u044F\0"
	/*  3825 */ "\u0421\u0432\u0435\u0442\u043B\u0430\u044F\0"
	/*  3840 */ "\u0412\u043A\u043B\0"
	/*  3847 */ "\u0412\u044B\u043A\u043B\0"
	/*  3856 */ "\u0420\u0430\u0437\u043C\u0435\u0440\0"
	/*  3869 */ "\u0428\u0440\u0438\u0444\u0442\0"
	/*  3880 */ "\u0421\u043B\u043E\u0432\u0430-\u0442\u0435\u043D\u0438\0"
	/*  3900 */ "\u041A\u0440\u0430\u0441\u043D\u044B\u0439\0"
	/*  3915 */ "\u0422\u0440\u0435\u043A\u0438\u043D\u0433\0"
	/*  3930 */ "\u042F\u043A\u043E\u0440\u044C\0"
	/*  3941 */ "\u0428\u0438\u0440\u0438\u043D\u0430 \u0433\u0438\u0434\u0430\0"
	/*  3963 */ "\u0417\u0430\u0437\u043E\u0440 \u0433\u0438\u0434\u0430\0"
	/*  3983 */ "\u0421\u0431\u0440\u043E\u0441\0"
	/*  3994 */ "\u043A\u043E\u0441\u043D\u0438\u0441\u044C \u0432\u044B\u0445\u043E\u0434\0"
	/*  4020 */ "\u043A\u043E\u0441\u043D\u0438\u0441\u044C \u0441\u0431\u0440\u043E\u0441\0"
	/*  4046 */ "\u0422\u0430\u043F \u0441\u043C\u0435\u043D\u0430  \u041B/\u041F \u043F\u0440\u0438\u043C\u0435\u0440\0"
	/*  4084 */ "\u0422\u0430\u043F \u0432\u044B\u0445\u043E\u0434  \u041B/\u041F \u043F\u0440\u0438\u043C\u0435\u0440\0"
	/*  4122 */ "\u0422\u0430\u043F \u0432\u043A\u043B  \u041B/\u041F \u043F\u0440\u0438\u043C\u0435\u0440\0"
	/*  4156 */ "\u0422\u0430\u043F \u0446\u0438\u043A\u043B  \u041B/\u041F \u043F\u0440\u0438\u043C\u0435\u0440\0"
	/*  4192 */ "\u0422\u0435\u043A\u0443\u0449\u0430\u044F \u043A\u043D\u0438\u0433\u0430\0"
	/*  4218 */ "\u041D\u0430\u0447\u0430\u043B\u043E\0"
	/*  4231 */ "\u041D\u0430\u0447\u0430\u043B\u043E \u043A\u043D\u0438\u0433\u0438\0"
	/*  4255 */ "\u0417\u0430\u043D\u043E\u0432\u043E \u043A\u043D\u0438\u0433\u0443\0"
	/*  4279 */ "\u0412\u044B \u0443\u0432\u0435\u0440\u0435\u043D\u044B?\0"
	/*  4300 */ "\u041D\u0435\u0442, \u043E\u0441\u0442\u0430\u0432\u0438\u0442\u044C\0"
	/*  4325 */ "\u0414\u0430, \u0437\u0430\u043D\u043E\u0432\u043E\0"
	/*  4344 */ "\u041D\u0435\u0442 \u043E\u0431\u0440\u0430\u0437\u0446\u043E\u0432\0"
	/*  4368 */ "\u0411\u043E\u043B\u044C\u0448\u043E\u0439\0"
	/*  4383 */ "\u0421\u0440\u0435\u0434\u043D\u0438\u0439\0"
	/*  4398 */ "\u041C\u0430\u043B\u0435\u043D\u044C\u043A\u0438\u0439\0"
	/*  4417 */ "\u0421\u0442\u0430\u043D\u0434\u0430\u0440\u0442\0"
	/*  4434 */ "\u041F\u0440\u043E\u043A\u0440\u0443\u0442\u043A\u0430\0"
	/*  4453 */ "\u041E\u0446\u0435\u043D\u043A\u0430 \u0432\u0440\u0435\u043C.\0"
	/*  4476 */ "\u0422\u043E\u0447\u043D\u043E\0"
	/*  4487 */ "\u0411\u044B\u0441\u0442\u0440\u043E\0";

constexpr std::array<uint16_t, kLanguageCount> kLanguageNameOffsets = {{
	/* English  */ 0,
	/* Spanish  */ 8,
	/* French   */ 16,
	/* German   */ 25,
	/* Romanian */ 33,
	/* Polish   */ 40,
	/* Russian  */ 47,
}};

using TextOffsetRow = std::array<uint16_t, kTextCount>;
using TextOffsetTable = std::array<TextOffsetRow, kLanguageCount>;

constexpr TextOffsetTable kTextOffsets = {{
	// English (en)
	{{
		/* Resume                   */ 62,
		/* Chapters                 */ 69,
		/* Library                  */ 78,
		/* Settings                 */ 86,
		/* UsbTransfer              */ 95,
		/* PowerOff                 */ 108,
		/* Back                     */ 118,
		/* Display                  */ 123,
		/* TypographyTune           */ 131,
		/* WordPacing               */ 147,
		/* Theme                    */ 159,
		/* Brightness               */ 165,
		/* Language                 */ 176,
		/* ReadingMode              */ 185,
		/* LongWords                */ 198,
		/* Complexity               */ 209,
		/* Punctuation              */ 220,
		/* ResetPacing              */ 232,
		/* Night                    */ 245,
		/* Dark                     */ 251,
		/* Light                    */ 256,
		/* On                       */ 262,
		/* Off                      */ 265,
		/* FontSize                 */ 269,
		/* Typeface                 */ 279,
		/* PhantomWords             */ 288,
		/* RedHighlight             */ 302,
		/* Tracking                 */ 316,
		/* Anchor                   */ 325,
		/* GuideWidth               */ 332,
		/* GuideGap                 */ 344,
		/* Reset                    */ 354,
		/* Typography               */ 360,
		/* TapToExit                */ 371,
		/* TapToReset               */ 383,
		/* TapChangeSample          */ 396,
		/* TapExitSample            */ 419,
		/* TapToggleSample          */ 440,
		/* TapCycleSample           */ 463,
		/* CurrentBook              */ 485,
		/* Start                    */ 498,
		/* StartOfBook              */ 504,
		/* RestartBook              */ 518,
		/* AreYouSure               */ 531,
		/* NoKeepPlace              */ 545,
		/* YesRestart               */ 560,
		/* NoSamples                */ 573,
		/* Large                    */ 584,
		/* Medium                   */ 590,
		/* Small                    */ 597,
		/* Standard                 */ 603,
		/* RsvpMode                 */ 612,
		/* ScrollMode               */ 617,
		/* TimeEstimate             */ 629,
		/* TimeEstimateAccurate     */ 643,
		/* TimeEstimateFast         */ 652,
	}},
	// Spanish (es)
	{{
		/* Resume                   */ 657,
		/* Chapters                 */ 666,
		/* Library                  */ 676,
		/* Settings                 */ 687,
		/* UsbTransfer              */ 695,
		/* PowerOff                 */ 699,
		/* Back                     */ 706,
		/* Display                  */ 712,
		/* TypographyTune           */ 721,
		/* WordPacing               */ 732,
		/* Theme                    */ 746,
		/* Brightness               */ 751,
		/* Language                 */ 758,
		/* ReadingMode              */ 765,
		/* LongWords                */ 778,
		/* Complexity               */ 794,
		/* Punctuation              */ 806,
		/* ResetPacing              */ 817,
		/* Night                    */ 835,
		/* Dark                     */ 841,
		/* Light                    */ 848,
		/* On                       */ 854,
		/* Off                      */ 857,
		/* FontSize                 */ 860,
		/* Typeface                 */ 867,
		/* PhantomWords             */ 874,
		/* RedHighlight             */ 892,
		/* Tracking                 */ 897,
		/* Anchor                   */ 907,
		/* GuideWidth               */ 913,
		/* GuideGap                 */ 924,
		/* Reset                    */ 935,
		/* Typography               */ 721,
		/* TapToExit                */ 947,
		/* TapToReset               */ 958,
		/* TapChangeSample          */ 973,
		/* TapExitSample            */ 998,
		/* TapToggleSample          */ 1021,
		/* TapCycleSample           */ 1047,
		/* CurrentBook              */ 1070,
		/* Start                    */ 1083,
		/* StartOfBook              */ 1090,
		/* RestartBook              */ 1107,
		/* AreYouSure               */ 1123,
		/* NoKeepPlace              */ 1131,
		/* YesRestart               */ 1145,
		/* NoSamples                */ 1159,
		/* Large                    */ 1172,
		/* Medium                   */ 1179,
		/* Small                    */ 1187,
		/* Standard                 */ 1195,
		/* RsvpMode                 */ 612,
		/* ScrollMode               */ 1204,
		/* TimeEstimate             */ 1218,
		/* TimeEstimateAccurate     */ 1234,
		/* TimeEstimateFast         */ 1242,
	}},
	// French (fr)
	{{
		/* Resume                   */ 1249,
		/* Chapters                 */ 1259,
		/* Library                  */ 1269,
		/* Settings                 */ 1282,
		/* UsbTransfer              */ 695,
		/* PowerOff                 */ 1291,
		/* Back                     */ 1300,
		/* Display                  */ 1307,
		/* TypographyTune           */ 1317,
		/* WordPacing               */ 1329,
		/* Theme                    */ 159,
		/* Brightness               */ 1341,
		/* Language                 */ 1352,
		/* ReadingMode              */ 1359,
		/* LongWords                */ 1372,
		/* Complexity               */ 1383,
		/* Punctuation              */ 1394,
		/* ResetPacing              */ 1406,
		/* Night                    */ 1421,
		/* Dark                     */ 1426,
		/* Light                    */ 1433,
		/* On                       */ 1439,
		/* Off                      */ 1443,
		/* FontSize                 */ 1447,
		/* Typeface                 */ 1454,
		/* PhantomWords             */ 1461,
		/* RedHighlight             */ 1475,
		/* Tracking                 */ 1488,
		/* Anchor                   */ 1499,
		/* GuideWidth               */ 1505,
		/* GuideGap                 */ 1519,
		/* Reset                    */ 1531,
		/* Typography               */ 1317,
		/* TapToExit                */ 1539,
		/* TapToReset               */ 1554,
		/* TapChangeSample          */ 1570,
		/* TapExitSample            */ 1598,
		/* TapToggleSample          */ 1626,
		/* TapCycleSample           */ 1654,
		/* CurrentBook              */ 1681,
		/* Start                    */ 1694,
		/* StartOfBook              */ 1700,
		/* RestartBook              */ 1715,
		/* AreYouSure               */ 1730,
		/* NoKeepPlace              */ 1742,
		/* YesRestart               */ 1754,
		/* NoSamples                */ 1768,
		/* Large                    */ 1782,
		/* Medium                   */ 1788,
		/* Small                    */ 1794,
		/* Standard                 */ 603,
		/* RsvpMode                 */ 612,
		/* ScrollMode               */ 1800,
		/* TimeEstimate             */ 1816,
		/* TimeEstimateAccurate     */ 1830,
		/* TimeEstimateFast         */ 1837,
	}},
	// German (de)
	{{
		/* Resume                   */ 1844,
		/* Chapters                 */ 1851,
		/* Library                  */ 1859,
		/* Settings                 */ 1870,
		/* UsbTransfer              */ 695,
		/* PowerOff                 */ 1879,
		/* Back                     */ 1891,
		/* Display                  */ 1898,
		/* TypographyTune           */ 1906,
		/* WordPacing               */ 1917,
		/* Theme                    */ 1927,
		/* Brightness               */ 1933,
		/* Language                 */ 1944,
		/* ReadingMode              */ 1952,
		/* LongWords                */ 1962,
		/* Complexity               */ 1975,
		/* Punctuation              */ 1987,
		/* ResetPacing              */ 1995,
		/* Night                    */ 2008,
		/* Dark                     */ 2014,
		/* Light                    */ 2021,
		/* On                       */ 2026,
		/* Off                      */ 2030,
		/* FontSize                 */ 2034,
		/* Typeface                 */ 2046,
		/* PhantomWords             */ 2057,
		/* RedHighlight             */ 2071,
		/* Tracking                 */ 2080,
		/* Anchor                   */ 2090,
		/* GuideWidth               */ 2096,
		/* GuideGap                 */ 2108,
		/* Reset                    */ 2119,
		/* Typography               */ 1906,
		/* TapToExit                */ 2132,
		/* TapToReset               */ 2148,
		/* TapChangeSample          */ 2165,
		/* TapExitSample            */ 2191,
		/* TapToggleSample          */ 2216,
		/* TapCycleSample           */ 2243,
		/* CurrentBook              */ 2270,
		/* Start                    */ 498,
		/* StartOfBook              */ 2285,
		/* RestartBook              */ 2296,
		/* AreYouSure               */ 2305,
		/* NoKeepPlace              */ 2313,
		/* YesRestart               */ 2326,
		/* NoSamples                */ 2334,
		/* Large                    */ 2347,
		/* Medium                   */ 2353,
		/* Small                    */ 2360,
		/* Standard                 */ 603,
		/* RsvpMode                 */ 612,
		/* ScrollMode               */ 2366,
		/* TimeEstimate             */ 2380,
		/* TimeEstimateAccurate     */ 2389,
		/* TimeEstimateFast         */ 2395,
	}},
	// Romanian (ro)
	{{
		/* Resume                   */ 2403,
		/* Chapters                 */ 2412,
		/* Library                  */ 676,
		/* Settings                 */ 2421,
		/* UsbTransfer              */ 695,
		/* PowerOff                 */ 2428,
		/* Back                     */ 2435,
		/* Display                  */ 2442,
		/* TypographyTune           */ 2449,
		/* WordPacing               */ 2460,
		/* Theme                    */ 746,
		/* Brightness               */ 2473,
		/* Language                 */ 2482,
		/* ReadingMode              */ 2488,
		/* LongWords                */ 2499,
		/* Complexity               */ 2513,
		/* Punctuation              */ 2526,
		/* ResetPacing              */ 2537,
		/* Night                    */ 2548,
		/* Dark                     */ 2555,
		/* Light                    */ 2562,
		/* On                       */ 2570,
		/* Off                      */ 2577,
		/* FontSize                 */ 2583,
		/* Typeface                 */ 2590,
		/* PhantomWords             */ 2595,
		/* RedHighlight             */ 2611,
		/* Tracking                 */ 2623,
		/* Anchor                   */ 2632,
		/* GuideWidth               */ 2639,
		/* GuideGap                 */ 2651,
		/* Reset                    */ 2663,
		/* Typography               */ 2449,
		/* TapToExit                */ 2672,
		/* TapToReset               */ 2686,
		/* TapChangeSample          */ 2699,
		/* TapExitSample            */ 2725,
		/* TapToggleSample          */ 2748,
		/* TapCycleSample           */ 2773,
		/* CurrentBook              */ 2797,
		/* Start                    */ 2812,
		/* StartOfBook              */ 2820,
		/* RestartBook              */ 2837,
		/* AreYouSure               */ 2855,
		/* NoKeepPlace              */ 2862,
		/* YesRestart               */ 2876,
		/* NoSamples                */ 2891,
		/* Large                    */ 2902,
		/* Medium                   */ 2907,
		/* Small                    */ 2913,
		/* Standard                 */ 603,
		/* RsvpMode                 */ 612,
		/* ScrollMode               */ 2917,
		/* TimeEstimate             */ 2933,
		/* TimeEstimateAccurate     */ 2944,
		/* TimeEstimateFast         */ 2950,
	}},
	// Polish (pl)
	{{
		/* Resume                   */ 2956,
		/* Chapters                 */ 2962,
		/* Library                  */ 2972,
		/* Settings                 */ 2983,
		/* UsbTransfer              */ 695,
		/* PowerOff                 */ 2994,
		/* Back                     */ 3001,
		/* Display                  */ 3006,
		/* TypographyTune           */ 3012,
		/* WordPacing               */ 3023,
		/* Theme                    */ 3034,
		/* Brightness               */ 3040,
		/* Language                 */ 3048,
		/* ReadingMode              */ 3054,
		/* LongWords                */ 3065,
		/* Complexity               */ 3078,
		/* Punctuation              */ 3088,
		/* ResetPacing              */ 3099,
		/* Night                    */ 3111,
		/* Dark                     */ 3115,
		/* Light                    */ 3122,
		/* On                       */ 3128,
		/* Off                      */ 3132,
		/* FontSize                 */ 3136,
		/* Typeface                 */ 3144,
		/* PhantomWords             */ 3149,
		/* RedHighlight             */ 3161,
		/* Tracking                 */ 3170,
		/* Anchor                   */ 3178,
		/* GuideWidth               */ 3186,
		/* GuideGap                 */ 3198,
		/* Reset                    */ 354,
		/* Typography               */ 3012,
		/* TapToExit                */ 3212,
		/* TapToReset               */ 3228,
		/* TapChangeSample          */ 3242,
		/* TapExitSample            */ 3268,
		/* TapToggleSample          */ 3294,
		/* TapCycleSample           */ 3321,
		/* CurrentBook              */ 3346,
		/* Start                    */ 498,
		/* StartOfBook              */ 3362,
		/* RestartBook              */ 3379,
		/* AreYouSure               */ 3395,
		/* NoKeepPlace              */ 3405,
		/* YesRestart               */ 3417,
		/* NoSamples                */ 3430,
		/* Large                    */ 3442,
		/* Medium                   */ 3447,
		/* Small                    */ 3454,
		/* Standard                 */ 603,
		/* RsvpMode                 */ 612,
		/* ScrollMode               */ 3459,
		/* TimeEstimate             */ 3473,
		/* TimeEstimateAccurate     */ 3488,
		/* TimeEstimateFast         */ 3497,
	}},
	// Russian (ru)
	{{
		/* Resume                   */ 3504,
		/* Chapters                 */ 3525,
		/* Library                  */ 3536,
		/* Settings                 */ 3557,
		/* UsbTransfer              */ 695,
		/* PowerOff                 */ 3576,
		/* Back                     */ 3595,
		/* Display                  */ 3606,
		/* TypographyTune           */ 3617,
		/* WordPacing               */ 3640,
		/* Theme                    */ 3658,
		/* Brightness               */ 3667,
		/* Language                 */ 3682,
		/* ReadingMode              */ 3691,
		/* LongWords                */ 3715,
		/* Complexity               */ 3741,
		/* Punctuation              */ 3760,
		/* ResetPacing              */ 3781,
		/* Night                    */ 3803,
		/* Dark                     */ 3812,
		/* Light                    */ 3825,
		/* On                       */ 3840,
		/* Off                      */ 3847,
		/* FontSize                 */ 3856,
		/* Typeface                 */ 3869,
		/* PhantomWords             */ 3880,
		/* RedHighlight             */ 3900,
		/* Tracking                 */ 3915,
		/* Anchor                   */ 3930,
		/* GuideWidth               */ 3941,
		/* GuideGap                 */ 3963,
		/* Reset                    */ 3983,
		/* Typography               */ 3617,
		/* TapToExit                */ 3994,
		/* TapToReset               */ 4020,
		/* TapChangeSample          */ 4046,
		/* TapExitSample            */ 4084,
		/* TapToggleSample          */ 4122,
		/* TapCycleSample           */ 4156,
		/* CurrentBook              */ 4192,
		/* Start                    */ 4218,
		/* StartOfBook              */ 4231,
		/* RestartBook              */ 4255,
		/* AreYouSure               */ 4279,
		/* NoKeepPlace              */ 4300,
		/* YesRestart               */ 4325,
		/* NoSamples                */ 4344,
		/* Large                    */ 4368,
		/* Medium                   */ 4383,
		/* Small                    */ 4398,
		/* Standard                 */ 4417,
		/* RsvpMode                 */ 612,
		/* ScrollMode               */ 4434,
		/* TimeEstimate             */ 4453,
		/* TimeEstimateAccurate     */ 4476,
		/* TimeEstimateFast         */ 4487,
	}},
}};

size_t languageIndex(UiLanguage language) {
	const size_t value = static_cast<size_t>(language);
	return value < kLanguageCount ? value : kDefaultLanguageIndex;
}

}  // namespace

namespace Localization {

UiLanguage sanitizeLanguage(uint8_t value) {
	if (value >= kLanguageCount) {
		return static_cast<UiLanguage>(kDefaultLanguageIndex);
	}
	return static_cast<UiLanguage>(value);
}

UiLanguage nextLanguage(UiLanguage current) {
	const size_t value = languageIndex(current);
	return static_cast<UiLanguage>((value + 1) % kLanguageCount);
}

const char *languageName(UiLanguage language) {
	return &kStringBlob[kLanguageNameOffsets[languageIndex(language)]];
}

const char *text(UiLanguage language, UiText key) {
	const size_t textIndex = static_cast<size_t>(key);
	if (textIndex >= kTextCount) {
		return "";
	}

	const size_t lang = languageIndex(language);
	uint16_t offset = kTextOffsets[lang][textIndex];

	if (offset == kMissingOffset) {
		offset = kTextOffsets[kDefaultLanguageIndex][textIndex];
	}

	return offset == kMissingOffset ? "" : &kStringBlob[offset];
}

}  // namespace Localization
